In [14]:
import numpy as np
import pandas as pd 
import scipy as stats

### loading dataset

In [15]:
dataset = pd.read_csv('iris.csv')  

X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

display(X)
display(y)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Choose one random sample from each class (Setosa, Versicolor, and Virginica) which will act as the test data.

In [16]:

# Separate data into different classes
setosa_indices = np.where(y == 0)[0]
versicolor_indices = np.where(y == 1)[0]
virginica_indices = np.where(y == 2)[0]


# Choose one random sample from each class for X_test
setosa_test_index = np.random.choice(setosa_indices)
versicolor_test_index = np.random.choice(versicolor_indices)
virginica_test_index = np.random.choice(virginica_indices)

# Combine the chosen indices for X_test
X_test_indices = [setosa_test_index, versicolor_test_index, virginica_test_index]
print("X_test_indices",X_test_indices)

# Create the X_test and y_test sets
X_test = X[X_test_indices]
y_test = y[X_test_indices]

# Create the X_train and y_train sets using the remaining data
X_train_indices = np.setdiff1d(np.arange(len(X)), X_test_indices)
X_train = X[X_train_indices]
y_train = y[X_train_indices]


print("X_train",X_train)
print("y_train",y_train)

print("X_test",X_test)
print("y_test",y_test)

# Print the shapes of the sets
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)


X_test_indices [38, 55, 100]
X_train [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5

## Compute the mean vector and covariance matrix for each class in the X_train

In [17]:

# Calculate the Mahalanobis distance for each sample in test
mean_vector_setosa = np.mean(X_train[y_train == 0], axis=0)
print("mean_vector of setosa:\n",mean_vector_setosa)
cov_matrix_setosa = np.cov(X_train[y_train == 0], rowvar=False)
print("covariance_mat of setosa:\n",cov_matrix_setosa)
inv_cov_matrix_setosa = np.linalg.inv(cov_matrix_setosa)
print("inv_cov of setosa:\n",inv_cov_matrix_setosa)

print("\n\n\n")

mean_vector_versicolor= np.mean(X_train[y_train == 1], axis=0)
print("mean_vector of versicolor:\n",mean_vector_versicolor)
cov_matrix_versicolor = np.cov(X_train[y_train == 1], rowvar=False)
print("covariance_mat of versicolor:\n",cov_matrix_versicolor)
inv_cov_matrix_versicolor = np.linalg.inv(cov_matrix_versicolor)
print("inv_cov of versicolor:\n",inv_cov_matrix_versicolor)

print("\n\n\n")

mean_vector_virginica = np.mean(X_train[y_train == 2], axis=0)
print("mean_vector of virginica:\n",mean_vector_virginica)
cov_matrix_virginica = np.cov(X_train[y_train == 2], rowvar=False)
print("covariance_mat of virginica:\n",cov_matrix_virginica)
inv_cov_matrix_virginica = np.linalg.inv(cov_matrix_virginica)
print("inv_cov of virginica:\n",inv_cov_matrix_virginica)



mean_vector of setosa:
 [5.01836735 3.42653061 1.46734694 0.24489796]
covariance_mat of setosa:
 [[0.11903061 0.09700255 0.01436224 0.01019983]
 [0.09700255 0.1444898  0.01046769 0.01128401]
 [0.01436224 0.01046769 0.03016156 0.00566327]
 [0.01019983 0.01128401 0.00566327 0.01169218]]
inv_cov of setosa:
 [[ 19.27578656 -12.41206619  -4.35933267  -2.72522079]
 [-12.41206619  15.52890475   1.43212753  -4.8526401 ]
 [ -4.35933267   1.43212753  37.70847186 -15.84382251]
 [ -2.72522079  -4.8526401  -15.84382251 100.26206658]]




mean_vector of versicolor:
 [5.94081633 2.76938776 4.25510204 1.32653061]
covariance_mat of versicolor:
 [[0.27079932 0.08710884 0.18791241 0.05681122]
 [0.08710884 0.1005017  0.08422194 0.04207908]
 [0.18791241 0.08422194 0.22419218 0.07475765]
 [0.05681122 0.04207908 0.07475765 0.03990646]]
inv_cov of versicolor:
 [[  9.77031542  -3.84972796  -9.21463718   7.41218501]
 [ -3.84972796  19.44255263   2.48164733 -19.66947405]
 [ -9.21463718   2.48164733  20.64818975 

## calculation of  mahalanobis distance of 'x_test' samples to corresponding distance to each class

In [18]:
matrix = []
mahalanobis_setosa = []
mahalanobis_versicolor = []
mahalanobis_virginica = []

for row in X_test:
    diff = row - mean_vector_setosa
    mahalanobis_dist = np.sqrt(np.dot(np.dot(diff, inv_cov_matrix_setosa),diff.T))
    mahalanobis_setosa.append(mahalanobis_dist)

matrix.append(mahalanobis_setosa)

for row in X_test:
    diff = row - mean_vector_versicolor
    mahalanobis_dist = np.sqrt(np.dot(np.dot(diff, inv_cov_matrix_versicolor),diff.T))
    mahalanobis_versicolor.append(mahalanobis_dist)

matrix.append(mahalanobis_versicolor)

for row in X_test:
    diff = row - mean_vector_virginica
    mahalanobis_dist = np.sqrt(np.dot(np.dot(diff, inv_cov_matrix_virginica),diff.T))
    mahalanobis_virginica.append(mahalanobis_dist)

matrix.append(mahalanobis_virginica)


# Define row names
row_names = ['setosa_mahalanobis', 'versicolor_mahalanobis', 'virginica_mahalanobis']

# Define column names
column_names = ['test_sample_1', 'test_sample_2', 'test_sample_3']

# Create a DataFrame from the matrix
df = pd.DataFrame(matrix, columns=column_names, index=row_names)

# Print the DataFrame(df)
display(df)

test_sample_1  test_sample_2  test_sample_3
setosa_mahalanobis           1.906161      19.018705      30.518239
versicolor_mahalanobis       8.946463       1.886492       6.982940
virginica_mahalanobis       12.384471       3.236802       3.315570

## Compare the Mahalanobis distances for the three samples and classify each sample to the class with the smallest Mahalanobis distance.


In [19]:


# Initialize a list to store the indices of minimum values in each column
y_pred = []
maha = []

# Get the number of columns in the matrix
num_columns = len(matrix[0])

for col in range(num_columns):
    min_value = matrix[0][col]
    min_index = 0

    # Loop through each row in the column
    for row in range(1, len(matrix)):
        if matrix[row][col] < min_value:
            min_value = matrix[row][col]
            min_index = row
    
    y_pred.append(min_index)
    maha.append(min_value)

# Print the indices of minimum values in each column
print("Indices of minimum values in each column (y_pred) :", y_pred)


Indices of minimum values in each column (y_pred) : [0, 1, 2]


## Print the original class and the predicted class for each sample, along with their Mahalanobis distances.


In [29]:
mat =[]
# because y_test will be like [0 1 2] we want to convert like [0,1,2]
new_ytest = [y_test[0],y_test[1],y_test[2]]

mat.append(new_ytest)
mat.append(y_pred)
mat.append(maha)

# Define column names
column_names = ['test_sample_1', 'test_sample_2', 'test_sample_3']

# Define column names
row_names = ['y_test', 'y_pred', 'mahalanobis_distance']

# Create a DataFrame from the matrix
df1 = pd.DataFrame(mat, columns=column_names,index = row_names)

# Print the DataFrame(df)
display(df1)


test_sample_1  test_sample_2  test_sample_3
y_test                     0.000000       1.000000        2.00000
y_pred                     0.000000       1.000000        2.00000
mahalanobis_distance       1.906161       1.886492        3.31557

## accuracy of your classifier on the testing set and report the results.

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("percent accuracy score : ",accuracy_score(y_test, y_pred)*100)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
percent accuracy score :  100.0
